"""no met col

Revision ID: 0904ef1eacef
Revises: 7376e7cf59ec
Create Date: 2023-08-18 20:04:28.221208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0904ef1eacef'
down_revision = '7376e7cf59ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('met_value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('met_value', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
