"""tables

Revision ID: a387268bd964
Revises: 
Create Date: 2023-08-16 19:41:36.510475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a387268bd964'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('met_value', sa.Integer(), nullable=True),
    sa.Column('bmr', sa.Float(), nullable=True),
    sa.Column('total_burned_calories', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_timestamp'), ['timestamp'], unique=False)

    op.create_table('body',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estimated_fitness_age', sa.Integer(), nullable=True),
    sa.Column('blood_pressure', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('body_temperature', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('body', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_body_timestamp'), ['timestamp'], unique=False)

    op.create_table('sleep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_REM_events', sa.Integer(), nullable=True),
    sa.Column('num_wakeup_events', sa.Integer(), nullable=True),
    sa.Column('sleep_efficiency', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sleep', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sleep_timestamp'), ['timestamp'], unique=False)

    op.create_table('health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('body_id', sa.Integer(), nullable=True),
    sa.Column('sleep_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['body_id'], ['body.id'], ),
    sa.ForeignKeyConstraint(['sleep_id'], ['sleep.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('genre', sa.String(length=128), nullable=True),
    sa.Column('health_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['health_id'], ['health.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('health')
    with op.batch_alter_table('sleep', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sleep_timestamp'))

    op.drop_table('sleep')
    with op.batch_alter_table('body', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_body_timestamp'))

    op.drop_table('body')
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_timestamp'))

    op.drop_table('activity')
    # ### end Alembic commands ###
